"""
radar_pipeline_demo.py

End-to-end demo of the full Python radar DSP prototype:

    simulated raw IQ  --> range FFT --> Doppler FFT --> CA-CFAR
                       --> angle estimation --> object list

Produces:
    results/range_doppler_map.png
    results/cfar_detection.png
    results/object_list.txt
    c_embedded/include/test_vectors.h   (exported test data for the C port)

Run from the python_model/ directory:
    python3 radar_pipeline_demo.py
"""

import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from generate_fmcw_data import RadarConfig, Target, generate_iq_cube
from range_fft import range_fft, range_axis
from doppler_fft import doppler_fft, doppler_axis, range_doppler_magnitude
from cfar import CfarConfig, ca_cfar_2d, cluster_detections
from angle_estimation import estimate_angles

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(THIS_DIR, "..", "results")
C_INCLUDE_DIR = os.path.join(THIS_DIR, "..", "c_embedded", "include")


def run_pipeline():
    cfg = RadarConfig()
    targets = [
        Target(range_m=18.0, velocity_mps=12.0, angle_deg=10.0, amplitude=4.0),
        Target(range_m=30.0, velocity_mps=-8.0, angle_deg=-15.0, amplitude=2.5),
    ]

    iq_cube = generate_iq_cube(cfg, targets, snr_db=15.0)

    r_cube = range_fft(iq_cube, cfg)
    rd_cube = doppler_fft(r_cube, cfg)
    mag_map = range_doppler_magnitude(rd_cube)

    cfar_cfg = CfarConfig(num_train=8, num_guard=4, pfa=1e-3)
    raw_dets, threshold_map = ca_cfar_2d(mag_map, cfar_cfg)
    dets = cluster_detections(raw_dets, mag_map, min_separation=3)
    angles = estimate_angles(rd_cube, dets, cfg)

    r_axis = range_axis(cfg)
    d_axis = doppler_axis(cfg)

    objects = []
    for (d_idx, r_idx), angle in zip(dets, angles):
        objects.append({
            "range_m": float(r_axis[r_idx]),
            "velocity_mps": float(d_axis[d_idx]),
            "angle_deg": angle,
            "magnitude": float(mag_map[d_idx, r_idx]),
        })

    return cfg, targets, mag_map, threshold_map, r_axis, d_axis, dets, objects


def save_range_doppler_plot(mag_map, r_axis, d_axis, path):
    mag_db = 20 * np.log10(mag_map + 1e-6)
    plt.figure(figsize=(7, 5))
    plt.imshow(
        mag_db,
        aspect="auto",
        origin="lower",
        extent=[r_axis[0], r_axis[-1], d_axis[0], d_axis[-1]],
        cmap="viridis",
    )
    plt.colorbar(label="Magnitude [dB]")
    plt.xlabel("Range [m]")
    plt.ylabel("Velocity [m/s]")
    plt.title("Range-Doppler Map")
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()


def save_cfar_plot(mag_map, r_axis, d_axis, dets, path):
    mag_db = 20 * np.log10(mag_map + 1e-6)
    plt.figure(figsize=(7, 5))
    plt.imshow(
        mag_db,
        aspect="auto",
        origin="lower",
        extent=[r_axis[0], r_axis[-1], d_axis[0], d_axis[-1]],
        cmap="viridis",
    )
    plt.colorbar(label="Magnitude [dB]")
    if dets:
        det_ranges = [r_axis[r] for _, r in dets]
        det_vels = [d_axis[d] for d, _ in dets]
        plt.scatter(det_ranges, det_vels, s=120, facecolors="none",
                    edgecolors="red", linewidths=2, label="CA-CFAR detection")
        plt.legend(loc="upper right")
    plt.xlabel("Range [m]")
    plt.ylabel("Velocity [m/s]")
    plt.title("CA-CFAR Detections on Range-Doppler Map")
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()


def export_test_vectors_for_c(cfg, iq_cube, path):
    """Export the full multi-antenna raw chirp cube as a C header with
    flat float arrays, so the embedded C pipeline can be validated
    against the exact same input the Python model used -- including
    the same non-coherent antenna integration -- which is the
    "design in Python, port and verify in C" workflow the role calls
    for. Flattened row-major as [antenna][chirp][sample].
    """
    real = iq_cube.real.astype(np.float32).flatten()
    imag = iq_cube.imag.astype(np.float32).flatten()

    def fmt_array(name, values):
        body = ", ".join(f"{v:.8f}f" for v in values)
        return f"static const float {name}[{len(values)}] = {{ {body} }};\n"

    with open(path, "w") as f:
        f.write("/* Auto-generated by radar_pipeline_demo.py -- do not edit by hand.\n")
        f.write(" * Full multi-antenna raw chirp cube, flattened row-major as\n")
        f.write(" * [antenna][chirp][sample], exported from the Python reference\n")
        f.write(" * model so the C pipeline can be validated against an identical\n")
        f.write(" * input, including the same non-coherent antenna integration. */\n\n")
        f.write("#ifndef TEST_VECTORS_H\n#define TEST_VECTORS_H\n\n")
        f.write(f"#define TV_NUM_RX      {cfg.num_rx}\n")
        f.write(f"#define TV_NUM_CHIRPS  {cfg.num_chirps}\n")
        f.write(f"#define TV_NUM_SAMPLES {cfg.num_samples}\n\n")
        f.write(fmt_array("TV_REAL", real))
        f.write(fmt_array("TV_IMAG", imag))
        f.write("\n#endif /* TEST_VECTORS_H */\n")


def export_python_timings_csv(cfg, path, n_runs=20):
    """Time each pure-Python pipeline stage and write the Python half
    of results/benchmark_table.csv. The C benchmark binary appends its
    own rows; see docs/performance_benchmark.md for the full picture.
    """
    import time

    targets = [Target(range_m=18.0, velocity_mps=12.0, angle_deg=10.0, amplitude=4.0)]
    iq_cube = generate_iq_cube(cfg, targets)

    def timeit(fn, *args, n=n_runs):
        # one warm-up call, then average over n_runs
        fn(*args)
        t0 = time.perf_counter()
        for _ in range(n):
            fn(*args)
        return (time.perf_counter() - t0) / n * 1e6  # microseconds

    t_range = timeit(range_fft, iq_cube, cfg)
    r_cube = range_fft(iq_cube, cfg)
    t_doppler = timeit(doppler_fft, r_cube, cfg)
    rd_cube = doppler_fft(r_cube, cfg)
    mag_map = range_doppler_magnitude(rd_cube)
    t_cfar = timeit(ca_cfar_2d, mag_map, CfarConfig())

    rows = [
        ("range_fft", "python", round(t_range, 2)),
        ("doppler_fft", "python", round(t_doppler, 2)),
        ("ca_cfar_2d", "python", round(t_cfar, 2)),
    ]
    with open(path, "w") as f:
        f.write("stage,implementation,avg_time_us\n")
        for stage, impl, t in rows:
            f.write(f"{stage},{impl},{t}\n")
    return rows


def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    os.makedirs(C_INCLUDE_DIR, exist_ok=True)

    cfg, targets, mag_map, threshold_map, r_axis, d_axis, dets, objects = run_pipeline()

    print("=== Radar configuration ===")
    print(f"  Range resolution   : {cfg.range_resolution:.3f} m")
    print(f"  Max unambiguous range: {cfg.max_range:.1f} m")
    print(f"  Velocity resolution : {cfg.velocity_resolution:.3f} m/s")
    print(f"  Max unambiguous velocity: {cfg.max_velocity:.1f} m/s")
    print()
    print("=== Ground truth targets ===")
    for t in targets:
        print(f"  range={t.range_m} m, velocity={t.velocity_mps} m/s, angle={t.angle_deg} deg")
    print()
    print("=== CA-CFAR detections -> objects ===")
    for obj in objects:
        print(f"  range={obj['range_m']:.2f} m, velocity={obj['velocity_mps']:.2f} m/s, "
              f"angle={obj['angle_deg']:.1f} deg, mag={obj['magnitude']:.2f}")

    save_range_doppler_plot(mag_map, r_axis, d_axis,
                             os.path.join(RESULTS_DIR, "range_doppler_map.png"))
    save_cfar_plot(mag_map, r_axis, d_axis, dets,
                    os.path.join(RESULTS_DIR, "cfar_detection.png"))

    with open(os.path.join(RESULTS_DIR, "object_list.txt"), "w") as f:
        f.write("range_m,velocity_mps,angle_deg,magnitude\n")
        for obj in objects:
            f.write(f"{obj['range_m']:.3f},{obj['velocity_mps']:.3f},"
                     f"{obj['angle_deg']:.2f},{obj['magnitude']:.3f}\n")

    export_test_vectors_for_c(cfg, generate_iq_cube(cfg, targets), os.path.join(C_INCLUDE_DIR, "test_vectors.h"))
    py_rows = export_python_timings_csv(cfg, os.path.join(RESULTS_DIR, "benchmark_table.csv"))

    print()
    print("=== Python stage timings (avg over 20 runs) ===")
    for stage, impl, t in py_rows:
        print(f"  {stage:12s} {impl:8s} {t:8.2f} us")

    print()
    print("Saved: results/range_doppler_map.png")
    print("Saved: results/cfar_detection.png")
    print("Saved: results/object_list.txt")
    print("Saved: results/benchmark_table.csv (Python rows)")
    print("Saved: c_embedded/include/test_vectors.h")


if __name__ == "__main__":
    main()
